// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/playground": {
    params: {};
  };
  "/telemetry": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/playground" | "/telemetry" | "/*";
  };
  "routes/[playground]._index.jsx": {
    id: "routes/[playground]._index";
    page: "/playground";
  };
  "routes/[telemetry]._index.jsx": {
    id: "routes/[telemetry]._index";
    page: "/telemetry";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[playground]._index": typeof import("./app/routes/[playground]._index.jsx");
  "routes/[telemetry]._index": typeof import("./app/routes/[telemetry]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};